require('dotenv').config();
const Anthropic = require('@anthropic-ai/sdk');
const logger = require('../utils/logger');
const { retry } = require('../utils/retry');

const MODEL = process.env.CLAUDE_MODEL || 'claude-sonnet-4-6';

const RASHI_ORDER = [
  ['♈', 'मेष'], ['♉', 'वृषभ'], ['♊', 'मिथुन'], ['♋', 'कर्क'],
  ['♌', 'सिंह'], ['♍', 'कन्या'], ['♎', 'तुला'], ['♏', 'वृश्चिक'],
  ['♐', 'धनु'], ['♑', 'मकर'], ['♒', 'कुंभ'], ['♓', 'मीन'],
];

const SYSTEM_PROMPT = `ROLE:
You are FactWala Astrology Content Generator.

TASK:
Generate content for an Instagram carousel post in Hindi.

OUTPUT FORMAT:
Return ONLY valid JSON, no markdown, no explanation, no text outside the JSON.

POST TYPE:
Daily Rashifal

LANGUAGE:
Pure Hindi (Devanagari Script)

TOTAL SLIDES:
3

SLIDE SIZE:
1080x1080

DESIGN STYLE:
Premium Astrology Theme, Dark Blue + Gold, Clean Typography, High Readability, Instagram Friendly

CONTENT RULES:
1. Total 12 Rashi cover karni hain.
2. Har slide me exactly 4 Rashi hongi.
3. Har Rashi ke saath uska symbol jarur include karein.
4. Har Rashi ke liye total content maximum 35-45 words (career + money + love + advice combined).
5. Content engaging aur positive hona chahiye.
6. Har Rashi me ye 4 sections hone chahiye: career, money (Dhan), love (Prem), advice (Salah).
7. Generic content nahi hona chahiye — har Rashi ka content unique aur specific ho.
8. Har din fresh content generate karein — aaj ki date ke hisaab se.
9. Content aisa lage ki user specifically apni rashi padh raha hai.
10. Koi disclaimer ya astrology warning mat likhein.

RASHI ORDER (use exactly these symbols and names, in this order):
Slide 1: ♈ मेष, ♉ वृषभ, ♊ मिथुन, ♋ कर्क
Slide 2: ♌ सिंह, ♍ कन्या, ♎ तुला, ♏ वृश्चिक
Slide 3: ♐ धनु, ♑ मकर, ♒ कुंभ, ♓ मीन

OUTPUT JSON SHAPE:
{
  "post_title": "आज का राशिफल",
  "date": "...",
  "slides": [
    {
      "slide": 1,
      "title": "मेष से कर्क",
      "rashis": [
        { "symbol": "♈", "name": "मेष", "career": "...", "money": "...", "love": "...", "advice": "..." },
        ... 3 more
      ]
    },
    { "slide": 2, "title": "सिंह से वृश्चिक", "rashis": [ ... 4 ] },
    { "slide": 3, "title": "धनु से मीन", "rashis": [ ... 4 ] }
  ],
  "caption": "..."
}

CAPTION RULES:
- Hindi, 1-2 lines, engaging, end with relevant hashtags
- Always include: #Rashifal #AajKaRashifal #FactWala

STRICTLY FORBIDDEN:
- No English words except proper nouns
- No markdown in output
- No text outside JSON
- No more or less than 3 slides, no more or less than 4 Rashi per slide`;

function buildUserPrompt(dateStr) {
  return `DATE:\n${dateStr}\n\nGenerate today's Rashifal carousel JSON for this date.`;
}

async function generateRashifal(dateStr) {
  const apiKey = process.env.CLAUDE_API_KEY;
  if (!apiKey) throw new Error('CLAUDE_API_KEY environment variable is not set');

  const client = new Anthropic({ apiKey });

  logger.info(`Generating Rashifal with Claude (${MODEL})...`, { date: dateStr });

  const response = await retry(
    () => client.messages.create({
      model:      MODEL,
      max_tokens: 4096,
      system:     SYSTEM_PROMPT,
      messages: [
        { role: 'user', content: buildUserPrompt(dateStr) },
      ],
    }),
    { attempts: 3, delayMs: 2000, label: 'Claude AI rashifal' }
  );

  const raw = response.content?.[0]?.text?.trim();
  if (!raw) throw new Error('Claude returned empty response');

  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch (e) {
    const match = raw.match(/\{[\s\S]*\}/);
    if (!match) throw new Error(`Could not extract JSON from Claude response: ${raw.substring(0, 200)}`);
    try {
      parsed = JSON.parse(match[0]);
    } catch (e2) {
      logger.error('Claude returned invalid JSON', { stopReason: response.stop_reason, raw });
      throw new Error(`Failed to parse Claude JSON response: ${e2.message}`);
    }
  }

  if (response.stop_reason === 'max_tokens') {
    logger.warn('Claude response was truncated at max_tokens — output may be incomplete');
  }

  const required = ['post_title', 'date', 'slides', 'caption'];
  for (const field of required) {
    if (!parsed[field]) throw new Error(`Claude response missing field: "${field}"`);
  }

  if (!Array.isArray(parsed.slides) || parsed.slides.length !== 3) {
    throw new Error(`Claude response must contain exactly 3 slides, got ${parsed.slides?.length}`);
  }

  let rashiIndex = 0;
  for (const slide of parsed.slides) {
    if (!Array.isArray(slide.rashis) || slide.rashis.length !== 4) {
      throw new Error(`Slide ${slide.slide} must contain exactly 4 rashis, got ${slide.rashis?.length}`);
    }
    for (const rashi of slide.rashis) {
      for (const field of ['symbol', 'name', 'career', 'money', 'love', 'advice']) {
        if (!rashi[field]) throw new Error(`Rashi "${rashi.name || '?'}" missing field: "${field}"`);
      }
      rashiIndex++;
    }
  }

  if (rashiIndex !== 12) throw new Error(`Expected 12 rashis total, got ${rashiIndex}`);

  logger.success('Rashifal generated by Claude', {
    model:        MODEL,
    date:         parsed.date,
    inputTokens:  response.usage?.input_tokens,
    outputTokens: response.usage?.output_tokens,
  });

  return parsed;
}

module.exports = { generateRashifal, RASHI_ORDER };
